<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>JS Promises</title>
  </head>
  <body>
    <div>
      <h1>JS Promises</h1>
      <p>
        Promise is for "eventual" completion of task. it is an object in
        JS.(solution of callback hell)
      </p>
      <h3>JS Promise object can be :</h3>
      <ol>
        <li>Pending: The result is undefined.</li>
        <li>Resolved: The result is a value, (fulfilled)</li>
        <li>Rejected: The result is an error object</li>
      </ol>
      <mark>The Promise object supports two properties: state and result.</mark>
      <h2>how to use a Promise:</h2>
      <p>
        Promise.then() takes two arguments, a callback for success and another
        for failure.
      </p>
      <p>resolve(value) — calls then() with the value (handles success).</p>
      <p>reject(error) — calls catch() with the error (handles failure).</p>
    </div>
    <div>
      <h2>Promise Chain</h2>
      <p>Used To perform multiple async tasks in order.
        A Promise chain is when you link multiple .then() methods together so
        that:
      </p>
      <ul>
        <li>Each .then() runs after the previous one finishes.</li>
        <li>The result of one .then() is passed to the next .then().</li>
        <li>If any step fails, the .catch() at the end can catch the error.</li>
      </ul>
    </div>
  </body>
  <script>
    // the promises are created by others,  we have to use or  handle the promises
    // resolve, reject are the callbacks provided by javascript
    let promise = new Promise((resolve, reject) => {
      console.log("I am a promise.");
      //resolve(12);
      // reject("error");
    });
    //console.log(promise); // pending, resolved, rejected

    // another example
    function getData(dataID) {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log("Data", dataID);
          resolve("Success");
        }, 2000);
      });
    }
    let resultPromise = getData(123);
    console.log(resultPromise);
    function checkPromise() {
      // after 2 seconds the state of promise will be updated to fulfilled.
      setTimeout(() => {
        console.log(resultPromise);
      }, 4000);
    }
    checkPromise();

    // use promise
    const getPromise = () => {
      return new Promise((resolve, reject) => {
        console.log("I am a promise.");
        resolve("Success");
        //reject("Error Occured!");
      });
    };
    const myPromise = getPromise();
    // call when promise  resolve.
    myPromise.then((res) => {
      console.log("Promise resolved: ", res);
    });
    // call when promise rejected.
    myPromise.catch((err) => {
      console.log("Promise rejected: ", err);
    });

    //Promise Chain -> use another then inside then
    function asyncFun1() {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log(" data1");
          resolve("Success");
        }, 4000);
      });
    }
    function asyncFun2() {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log("data2");
          resolve("Success");
        }, 4000);
      });
    }
    //promise chain....
    /* asyncFun1().then((res) => {
      console.log("data1 received");
      asyncFun2().then((res) => {
        console.log("data2 received");
      });
    }); */
    asyncFun1()
      .then((res) => {
        console.log(res);
        return asyncFun2();
      })
      .then((res) => {
        console.log(res);
      });
  </script>
</html>
